/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab_2;

/**
 *
 * @author N E Z U
 */
public class Bai_1 extends javax.swing.JFrame {

    /**
     * Creates new form Bai_1
     */
    public Bai_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        pnl1 = new javax.swing.JPanel();
        btnSo1 = new javax.swing.JButton();
        btnSo2 = new javax.swing.JButton();
        btnSo3 = new javax.swing.JButton();
        btnChia = new javax.swing.JButton();
        btnCanbac2 = new javax.swing.JButton();
        btnSo4 = new javax.swing.JButton();
        btnSo5 = new javax.swing.JButton();
        btnSo6 = new javax.swing.JButton();
        btnNhan = new javax.swing.JButton();
        btnPhantram = new javax.swing.JButton();
        btnSo7 = new javax.swing.JButton();
        btnSo8 = new javax.swing.JButton();
        btnSo9 = new javax.swing.JButton();
        btnTru = new javax.swing.JButton();
        btnMotphanx = new javax.swing.JButton();
        btnSo0 = new javax.swing.JButton();
        btnAmorDuong = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        btnCong = new javax.swing.JButton();
        btnDaubang = new javax.swing.JButton();
        pnl2 = new javax.swing.JPanel();
        hienThi = new javax.swing.JTextField();

        jButton8.setText("jButton8");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.BorderLayout());

        pnl1.setLayout(new java.awt.GridLayout(4, 5, 4, 0));

        btnSo1.setText("1");
        pnl1.add(btnSo1);

        btnSo2.setText("2");
        pnl1.add(btnSo2);

        btnSo3.setText("3");
        pnl1.add(btnSo3);

        btnChia.setText("/");
        pnl1.add(btnChia);

        btnCanbac2.setText("sqrt");
        pnl1.add(btnCanbac2);

        btnSo4.setText("4");
        pnl1.add(btnSo4);

        btnSo5.setText("5");
        pnl1.add(btnSo5);

        btnSo6.setText("6");
        pnl1.add(btnSo6);

        btnNhan.setText("*");
        pnl1.add(btnNhan);

        btnPhantram.setText("%");
        pnl1.add(btnPhantram);

        btnSo7.setText("7");
        pnl1.add(btnSo7);

        btnSo8.setText("8");
        pnl1.add(btnSo8);

        btnSo9.setText("9");
        pnl1.add(btnSo9);

        btnTru.setText("-");
        pnl1.add(btnTru);

        btnMotphanx.setText("1/x");
        pnl1.add(btnMotphanx);

        btnSo0.setText("0");
        pnl1.add(btnSo0);

        btnAmorDuong.setText("+/-");
        pnl1.add(btnAmorDuong);

        btnClean.setText("C");
        pnl1.add(btnClean);

        btnCong.setText("+");
        pnl1.add(btnCong);

        btnDaubang.setText("=");
        pnl1.add(btnDaubang);

        mainPanel.add(pnl1, java.awt.BorderLayout.CENTER);

        hienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hienThiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hienThi, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        mainPanel.add(pnl2, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hienThiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hienThiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmorDuong;
    private javax.swing.JButton btnCanbac2;
    private javax.swing.JButton btnChia;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnDaubang;
    private javax.swing.JButton btnMotphanx;
    private javax.swing.JButton btnNhan;
    private javax.swing.JButton btnPhantram;
    private javax.swing.JButton btnSo0;
    private javax.swing.JButton btnSo1;
    private javax.swing.JButton btnSo2;
    private javax.swing.JButton btnSo3;
    private javax.swing.JButton btnSo4;
    private javax.swing.JButton btnSo5;
    private javax.swing.JButton btnSo6;
    private javax.swing.JButton btnSo7;
    private javax.swing.JButton btnSo8;
    private javax.swing.JButton btnSo9;
    private javax.swing.JButton btnTru;
    private javax.swing.JTextField hienThi;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    // End of variables declaration//GEN-END:variables
}
